### ISSUE TITLE
Redo Docs

### ISSUE THREAD

**Issue by lukefahr** [Engr315/P1_Optimization#3]

**Comment by lukefahr** [comment]
make a copy of original doc.

**Comment by nonlaminar** [comment]
This has been done in a google doc -> [link](https://docs.google.com/document/d/105JyX49O5bt4fwf8lDtwJeOk-tv2ZoSdRi1HCloXQ2M/edit?usp=sharing)
[E315-P1-Optimization.pdf](https://github.com/Engr315/P1_Optimization/files/12386895/E315-P1-Optimization.pdf)
